spring:
  application:
    name: user-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
#  servlet:
#    context-path: /${spring.application.name}
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
