spring:
  application:
    name: account-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

account.greeting: Hello Cloud

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    git:
      mode: full
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
