spring:
  application:
    name: app-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/us-api/**
        filters:
          - RewritePath=/us-api(?<segment>/?.*), $\{segment}
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 2
              redis-rate-limiter.burstCapacity: 5
      - id: account-service
        uri: lb://account-service
        predicates:
          - Path=/as-api/**
        filters:
          - RewritePath=/as-api(?<segment>/?.*), $\{segment}
#          - name: RequestRateLimiter
#            args:
#              redis-rate-limiter.replenishRate: 5
#              redis-rate-limiter.burstCapacity: 10
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: false
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Spring Actuator Configurations
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    git:
      mode: full
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
logging:
  level:
    root: info
    org.springframework.cloud.gateway: debug
